"""Identifiers for the Calo Airtable base.

These are not secrets (base IDs are public identifiers). The actual API key
stays in the .env. Generated by the Airtable MCP setup; if you recreate the
base from scratch, refresh this file.
"""

BASE_ID = "appDlXTmOGVJ6ML6z"

# --- table IDs ---
USERS_TABLE = "tblN3Rc4XDpd8LJ1u"
FOODS_TABLE = "tblwQ2TOsmW7a8Wig"
KNOWLEDGE_TABLE = "tblXA4qxZbqw4v4xD"
MEALS_TABLE = "tblmw9BuImOaEkk8B"
WEIGHT_LOGS_TABLE = "tblOrpeTZf2cN770r"
BODY_PHOTOS_TABLE = "tblCmbR8w7BrLErqZ"
MEMORIES_TABLE = "tblSoqBsOGeUL20gd"
RECIPES_TABLE = "tblwPLplGlehhyWfj"
CHALLENGES_TABLE = "tbld6N7WUah20naa4"
USER_CHALLENGES_TABLE = "tbl8GGMKbL0DEJ9WR"
PROGRAMS_TABLE = "tbl0WbGOk2zplHeiU"
EXERCISES_TABLE = "tblDAceDl1prMuYtC"
WORKOUT_LOGS_TABLE = "tblYEUsumV7Gjit2Q"

# --- field IDs ---
# Using field IDs rather than names insulates Calo from renames in the Airtable UI.

USERS_FIELDS = {
    "whatsapp_number": "fldB8wA3IkF7Pte7N",
    "name": "fld311sYo6LwZfvFa",
    "sex": "fldjppP1MAPjmSkRg",
    "age": "fldWbIkUZxGzqV33i",
    "height_cm": "fldAHPGNRtpRDz5vz",
    "current_weight_kg": "fldJWXbKZFOZQX9ej",
    "activity_level": "fldiVIAsHYS50zIdx",
    "goal": "fldwE5ncyrSd0v0tH",
    "target_weight_kg": "fldmEBvy297EmGxWZ",
    "target_date": "fld9mWkVCrdEBg4BT",
    "restrictions": "fldeiNghr828TNV8j",
    "daily_calories": "fld5E2XbXhOUZy7nc",
    "daily_protein_g": "fldB1miZ2DrpOJMhs",
    "daily_carbs_g": "fldcKqbFNGEnZNXuG",
    "daily_fat_g": "fldE8TgL3pPeHRcBu",
    "photo_consent": "fldwIUIFp3XMWtdeo",
    "onboarding_complete": "fldH5BC9lkE0bKEBP",
    "admin_notes": "fldklbAHJU777IwR1",
    "created_at": "fldqF6aRQG3LcAKOO",
    # Adaptive metabolic profile — Calo learns over time
    "metabolic_history": "fldat12ppQGnAjSPo",
    "metabolic_type": "fldnvgJD2gmUkHFHu",
    "prior_diets_tried": "fldKlKdhV0PzkrOtK",
    "lifetime_lowest_kg": "fldjzSAWvWMNtck7g",
    "lifetime_highest_kg": "fldM0A1IUaiaREvfA",
    "current_meds": "fldhzjR3a8mn5t61S",
    "medical_conditions": "fld6ap3vy7h5AMLOq",
    "digestive_profile": "fldP6asxX3TZIfV8C",
    "sleep_quality": "fldlAqAc98VgaNhOI",
    "stress_level": "fldTPoRQbwkGHScBR",
    "calorie_adjustment": "fldaDY7VeBgMSGeTG",
    "last_calibration": "fld1gFFSgqmRm7mXa",
    "personal_patterns": "fldsCoMjczzqu9De6",
    "anamnese_started": "fldsrJLNR5N0gJbKh",
    # Sport + Mental modules
    "active_program": "fldsmsFaReGUtlE7K",
    "program_started_at": "fldXNOxNaY3hPM5ES",
    "personal_records": "fldgdhjiP5hl4EblZ",
    "mental_profile": "fldcOIPcvftlswNWN",
    "workouts_completed": "fldpA29njGU4MC1gD",
}

PROGRAMS_FIELDS = {
    "name": "fldxu9t2qleaCA3lr",
    "slug": "fldtfWgGwdyEq6Prh",
    "goal": "fldNNYXbWA263oerF",
    "duration_weeks": "fld7E2F4MRckM6uqS",
    "days_per_week": "fld6BcUBSTlbfXNll",
    "equipment": "fldCcUP9TNsZhVOiD",
    "difficulty": "fldWG9Vcbae1K57cC",
    "description": "fldn7LQJ9TKjQsw70",
    "weekly_structure": "fldltWC0jzO5KLnRC",
    "tags": "fld9YajoD0vWyLx2H",
    "active": "fldtPZWmMIuNwHgee",
    "created_at": "fld0C8Z24LdGQFQUB",
}

EXERCISES_FIELDS = {
    "name": "fld7vYzPtcOyeq9Og",
    "category": "fldFnhwa6p1ccNCFB",
    "equipment": "fldltgPb7TyxSMWsA",
    "difficulty": "fldNnWNrOkpr9rMCC",
    "primary_muscles": "fldPiIAqIVYUd34hc",
    "technique": "fld7W1wRJTFSBtXY9",
    "common_mistakes": "fldoHE9DjXtSdiNnb",
    "regressions": "fldK47TIiMirDask7",
    "progressions": "fld1sOzLzpBcOZQoT",
    "video_url": "fld7occ56RautxmPo",
    "active": "fldaSLXynBWvovemH",
    "contraindications": "fld5Jpr5aOhQuWqG1",
    "best_for": "fldkKOq774HAwTlS3",
}

WORKOUT_LOGS_FIELDS = {
    "session": "fld5Q3z8i8Li73GEy",
    "user": "fldg8GJokJM8RK1F2",
    "date": "fldKOK8XOutXbRJqv",
    "program": "fldiAL0J9p1PYBa46",
    "day_name": "fldY6ARbmOXlH48vp",
    "exercises_log": "fldfQ58LQ2Yjus3To",
    "duration_min": "fldBzolUW8dd3D8rs",
    "rpe": "fldLbQTNXtLElPRXh",
    "note": "fldXCKF0FVO2pKijN",
    "pr_hit": "fld7aBiRbDvQE26bn",
}

FOODS_FIELDS = {
    "name_fr": "fldZ3NKtJRWYqXYuz",
    "category": "flducGjY3tgWtnvMU",
    "kcal_per_100g": "flda7VUaI5XDvYITf",
    "protein_per_100g": "fldfvZ0Akisbkbspn",
    "carbs_per_100g": "fldLvOvnwFwFG0oG1",
    "fat_per_100g": "fldbQa7cjhY8setD9",
    "fiber_per_100g": "fldkAOgAxrNaeFjq1",
    "standard_portion_g": "fldHu4JVOsIpV1s64",
    "source": "fld1rvNLnJcEHecbm",
    "active": "fld9CUduT488ydPeg",
}

KNOWLEDGE_FIELDS = {
    "title": "fldnxDcnh4q5BIgOn",
    "topic": "fldPQjpTXya9opXBj",
    "content": "fldDMX7U6swUgi2RE",
    "tags": "fldQJQZ3anuN9XioB",
    "active": "fldXlGo2qiYRoKxq1",
    "created_at": "fld9lTfjLZWq1wazP",
}

MEALS_FIELDS = {
    "eaten_at": "fldYxAelfsMCpK9YE",
    "user": "fld1mQKcOV76tcEOt",
    "items": "fldfiLVNZgvE4VCqS",
    "total_calories": "fldyMuAYt6a240SaA",
    "total_protein_g": "fldzTpN1NpPS8qjL2",
    "total_carbs_g": "fldfXEUTJFNyhppoC",
    "total_fat_g": "fldgVxCJoLWeh8gU7",
    "photo": "fldrIkfnYjnuWphzC",
    "notes": "fldvkKQDgQyqIDzbx",
    "meal_type": "fld7g4K49JGI57uJZ",
}

WEIGHT_LOGS_FIELDS = {
    "logged_at": "flds3nHMRTJqLiIcp",
    "user": "fldHrrZm4WObmLuWy",
    "weight_kg": "fldc3UTHN2o1mewzv",
    "notes": "fldP4mbrZ2wkIoGvm",
}

BODY_PHOTOS_FIELDS = {
    "captured_at": "fldNns7MPZL4fvCKM",
    "user": "fldJgV6NqvXIJUNLv",
    "week_number": "fldxocNIURXwQPKbB",
    "encrypted_photo_ref": "fld0njqLVjIuoxUKD",
    "analysis": "fldut7Wpri3HRGMPS",
    "angle": "fldZWz3UAkfKvSTgQ",
}

MEMORIES_FIELDS = {
    "created_at": "fldj0nTX4YV0lDm4t",
    "user": "fldholfHLm6jMlSy2",
    "memory": "fldZ6CoPSSdvDlVs5",
    "category": "fld6QXWShaiBWIzVt",
    "importance": "fldlWyX7O2qKbmsk6",
    "active": "fld2YR3W4OdURVxGU",
    "admin_notes": "fld6jbIhdEegNL0Pk",
}

RECIPES_FIELDS = {
    "name": "fldWLyg1J6XzYS1BM",
    "category": "fldfbfEgOzkOOAYra",
    "tags": "fldRv4nVbaOW1tOII",
    "servings": "fldmUxrMKw8A8hFUb",
    "prep_min": "fld9fIiw8Q1PlDNfD",
    "cook_min": "fldFsYrBplWl9ywXz",
    "kcal": "fldAp1whWEysw9FhG",
    "protein_g": "fldp2r9TDkWP9ODMo",
    "carbs_g": "fldsTJKn6JIuGsB0x",
    "fat_g": "fldLYVaulM88VJzTz",
    "fiber_g": "fld4oUsNfsSbD5QZR",
    "ingredients": "flddeo9CTqw1NFEsC",
    "instructions": "fld2j49CNKLS5Fjps",
    "active": "fldc5zpzj71nXIcd6",
    "created_at": "fldx8fwAAw9UN56gU",
    "notes": "fldCnsxzEzTjsAq7K",
}

CHALLENGES_FIELDS = {
    "name": "fld5GsiOL108HPk5l",
    "slug": "fld2TTtEkujTCVFgk",
    "duration_days": "fldlI4CxNoYf03ZSM",
    "category": "fld1Za78hzb9uJ4sv",
    "difficulty": "fldgiJXdyGqojdkVP",
    "target_audience": "fldALLMdxt82GWmWm",
    "pitch": "fldYSEMhTNn27rE4U",
    "daily_structure": "fldbH5VYHpbHZLwJs",
    "rules": "fldvwSBrCZJ2k0cHP",
    "expected_outcome": "fldjQQwJFygIzz8Wi",
    "active": "fldSuFAdkljd4xiNs",
    "created_at": "fldQAnB5zs7Tc5tgn",
}

USER_CHALLENGES_FIELDS = {
    "started_at": "fldQ0cXuxeCgrKEoe",
    "user": "fldiM2LFIFDAeUMnJ",
    "challenge": "fldBmbmeConhrc0ZN",
    "status": "fldHf5SspM6ORBy7h",
    "current_day": "fldWNhpwJ0PqY3KWw",
    "adherence": "fldE8sEycuBQYMZoI",
    "notes": "fldBSnzqL8hxDa4Rt",
    "completed_at": "fldS0eTT77LHz3bpv",
}
