"""Identifiers for the Calo Airtable base.

These are not secrets (base IDs are public identifiers). The actual API key
stays in the .env. Generated by the Airtable MCP setup; if you recreate the
base from scratch, refresh this file.
"""

BASE_ID = "appDlXTmOGVJ6ML6z"

# --- table IDs ---
USERS_TABLE = "tblN3Rc4XDpd8LJ1u"
FOODS_TABLE = "tblwQ2TOsmW7a8Wig"
KNOWLEDGE_TABLE = "tblXA4qxZbqw4v4xD"
MEALS_TABLE = "tblmw9BuImOaEkk8B"
WEIGHT_LOGS_TABLE = "tblOrpeTZf2cN770r"
BODY_PHOTOS_TABLE = "tblCmbR8w7BrLErqZ"
MEMORIES_TABLE = "tblSoqBsOGeUL20gd"

# --- field IDs ---
# Using field IDs rather than names insulates Calo from renames in the Airtable UI.

USERS_FIELDS = {
    "whatsapp_number": "fldB8wA3IkF7Pte7N",
    "name": "fld311sYo6LwZfvFa",
    "sex": "fldjppP1MAPjmSkRg",
    "age": "fldWbIkUZxGzqV33i",
    "height_cm": "fldAHPGNRtpRDz5vz",
    "current_weight_kg": "fldJWXbKZFOZQX9ej",
    "activity_level": "fldiVIAsHYS50zIdx",
    "goal": "fldwE5ncyrSd0v0tH",
    "target_weight_kg": "fldmEBvy297EmGxWZ",
    "target_date": "fld9mWkVCrdEBg4BT",
    "restrictions": "fldeiNghr828TNV8j",
    "daily_calories": "fld5E2XbXhOUZy7nc",
    "daily_protein_g": "fldB1miZ2DrpOJMhs",
    "daily_carbs_g": "fldcKqbFNGEnZNXuG",
    "daily_fat_g": "fldE8TgL3pPeHRcBu",
    "photo_consent": "fldwIUIFp3XMWtdeo",
    "onboarding_complete": "fldH5BC9lkE0bKEBP",
    "admin_notes": "fldklbAHJU777IwR1",
    "created_at": "fldqF6aRQG3LcAKOO",
}

FOODS_FIELDS = {
    "name_fr": "fldZ3NKtJRWYqXYuz",
    "category": "flducGjY3tgWtnvMU",
    "kcal_per_100g": "flda7VUaI5XDvYITf",
    "protein_per_100g": "fldfvZ0Akisbkbspn",
    "carbs_per_100g": "fldLvOvnwFwFG0oG1",
    "fat_per_100g": "fldbQa7cjhY8setD9",
    "fiber_per_100g": "fldkAOgAxrNaeFjq1",
    "standard_portion_g": "fldHu4JVOsIpV1s64",
    "source": "fld1rvNLnJcEHecbm",
    "active": "fld9CUduT488ydPeg",
}

KNOWLEDGE_FIELDS = {
    "title": "fldnxDcnh4q5BIgOn",
    "topic": "fldPQjpTXya9opXBj",
    "content": "fldDMX7U6swUgi2RE",
    "tags": "fldQJQZ3anuN9XioB",
    "active": "fldXlGo2qiYRoKxq1",
    "created_at": "fld9lTfjLZWq1wazP",
}

MEALS_FIELDS = {
    "eaten_at": "fldYxAelfsMCpK9YE",
    "user": "fld1mQKcOV76tcEOt",
    "items": "fldfiLVNZgvE4VCqS",
    "total_calories": "fldyMuAYt6a240SaA",
    "total_protein_g": "fldzTpN1NpPS8qjL2",
    "total_carbs_g": "fldfXEUTJFNyhppoC",
    "total_fat_g": "fldgVxCJoLWeh8gU7",
    "photo": "fldrIkfnYjnuWphzC",
    "notes": "fldvkKQDgQyqIDzbx",
    "meal_type": "fld7g4K49JGI57uJZ",
}

WEIGHT_LOGS_FIELDS = {
    "logged_at": "flds3nHMRTJqLiIcp",
    "user": "fldHrrZm4WObmLuWy",
    "weight_kg": "fldc3UTHN2o1mewzv",
    "notes": "fldP4mbrZ2wkIoGvm",
}

BODY_PHOTOS_FIELDS = {
    "captured_at": "fldNns7MPZL4fvCKM",
    "user": "fldJgV6NqvXIJUNLv",
    "week_number": "fldxocNIURXwQPKbB",
    "encrypted_photo_ref": "fld0njqLVjIuoxUKD",
    "analysis": "fldut7Wpri3HRGMPS",
    "angle": "fldZWz3UAkfKvSTgQ",
}

MEMORIES_FIELDS = {
    "created_at": "fldj0nTX4YV0lDm4t",
    "user": "fldholfHLm6jMlSy2",
    "memory": "fldZ6CoPSSdvDlVs5",
    "category": "fld6QXWShaiBWIzVt",
    "importance": "fldlWyX7O2qKbmsk6",
    "active": "fld2YR3W4OdURVxGU",
    "admin_notes": "fld6jbIhdEegNL0Pk",
}
